### ISSUE TITLE
Erroneous computation of GeoPIP tree likelihood regarding geometric parameter

### ISSUE THREAD

**Issue by BernardYuan** [yzhai220/geopip#1]
https://github.com/yzhai220/geopip/blob/0cef61d436cbd861147af44f05e7d2bdcfcedf5f/src/geopip_est.py#L125-L126

These two lines correspond to the logarithm form of $(1-rho)^(# of segments -1 ) * rho $, which is from equation (3) of [GeoPIP paper](https://www.ncbi.nlm.nih.gov/pubmed/28204784).

I think the position of _p_ and _q_ should be reversed.

**Comment by yzhai220** [comment]
Thank you for pointing out! 

Yes, your are right. p and q should be switched. Correction is made. 
Given that geometric parameter is of minor importance in the likelihood calculation, this should not change results. Correction may improve accuracy in estimation on number of segments, if there is any impact on final results. 

Thank you again!
